#This file stores configuration options for Iris, such as the currently active shaderpack
#Sun Jun 21 17:51:03 MSK 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=0
shaderPack=ComplementaryReimagined_r5.2.2.zip
enableShaders=true
